# Generated by Django 5.1.1 on 2024-09-29 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_slug'),
    ]

    operations = [
    ]
