# Generated by Django 5.1.1 on 2024-09-29 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20240930_0216'),
    ]

    operations = [
    ]
