# Generated by Django 5.1.1 on 2024-09-29 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20240930_0217'),
    ]

    operations = [
    ]
